package uk.gov.justice.digital.hmpps.createandvaryalicenceapi.service.probation

data class OffenderDetail(
  val offenderId: Long,
  val otherIds: OtherIds,
  val offenderManagers: List<OffenderManager>,
  val accessDenied: Boolean? = null,
  val activeProbationManagedSentence: Boolean? = null,
  val age: Long? = null,
  val contactDetails: ContactDetails? = null,
  val currentDisposal: String? = null,
  val currentExclusion: Boolean? = null,
  val currentRestriction: Boolean? = null,
  val currentTier: String? = null,
  val dateOfBirth: String? = null,
  val exclusionMessage: String? = null,
  val firstName: String? = null,
  val gender: String? = null,
  val highlight: Map<String, String>? = mutableMapOf(),
  val mappa: List<MappaDetails>? = null,
  val middleNames: List<String>? = null,
  val offenderAliases: List<OffenderAlias>? = null,
  val offenderProfile: List<OffenderProfile>? = null,
  val partitionArea: String? = null,
  val previousSurname: String? = null,
  val probationStatus: List<ProbationStatus>? = null,
  val restrictionMessage: String? = null,
  val softDeleted: Boolean? = null,
  val surname: String? = null,
  val title: String? = null,
)
