package uk.gov.justice.digital.hmpps.createandvaryalicenceapi.service.probation

data class OffenderDetail(
  val offenderId: Long,
  val otherIds: OtherIds,
  val offenderManagers: List<OffenderManager>,
  val accessDenied: Boolean?,
  val activeProbationManagedSentence: Boolean?,
  val age: Long?,
  val contactDetails: ContactDetails?,
  val currentDisposal: String?,
  val currentExclusion: Boolean?,
  val currentRestriction: Boolean?,
  val currentTier: String?,
  val dateOfBirth: String?,
  val exclusionMessage: String?,
  val firstName: String?,
  val gender: String?,
  val highlight: Map<String, String>? = mutableMapOf(),
  val mappa: List<MappaDetails>?,
  val middleNames: List<String>?,
  val offenderAliases: List<OffenderAlias>?,
  val offenderProfile: List<OffenderProfile>?,
  val partitionArea: String?,
  val previousSurname: String?,
  val probationStatus: List<ProbationStatus>?,
  val restrictionMessage: String?,
  val softDeleted: Boolean?,
  val surname: String?,
  val title: String?,
)
