{{ $host := (index .Values "generic-service" "ingress" "host") }}
{{- range .Values.jobs }}
  {{- if .enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .cron }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 0
      parallelism: 1
      completions: 1
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
            - name: {{ .name }}-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail -X POST "https://$BASE_URL/jobs/{{ .path }}"
              env:
                - name: BASE_URL
                  value: {{  index $ "Values" "generic-service" "ingress" "hosts" 0 }}
{{- end }}
---
{{ end }}
