package uk.gov.justice.digital.hmpps.createandvaryalicenceapi.util

enum class LicenceEventType {
  CREATED,
  SUBMITTED,
  BACK_IN_PROGRESS,
  APPROVED,
  ACTIVATED,
  SUPERSEDED,
  HARDSTOP_CREATED,
  HARDSTOP_SUBMITTED,
  VARIATION_CREATED,
  VARIATION_SUBMITTED_REASON,
  VARIATION_IN_PROGRESS,
  VARIATION_SUBMITTED,
  VARIATION_REFERRED,
  VARIATION_APPROVED,
  INACTIVE,
  RECALLED,
  VERSION_CREATED,
  NOT_STARTED,
  TIMED_OUT,
}
