package uk.gov.justice.digital.hmpps.createandvaryalicenceapi.util

enum class RemandCourtEvents(val code: String) {
  BAIL_APPEAL_WITHDRAWN("2507"),
  COMMITTED_TO_CROWN_COURT_FOR_SENTENCE("4001"),
  SENTENCE_POSTPONED("4004"),
  REMITTAL_FOR_SENTENCE_IN_CUSTODY("4012"),
  COMMIT_TO_CROWN_COURT_FOR_SENTENCE_IN_CUSTODY("4016"),
  WARRANT_FOR_FURTHER_DETENTION("4505"),
  ADJOURNMENT("4506"),
  REMAND_IN_CUSTODY_BAIL_REFUSED("4531"),
  REMAND_IN_CUSTODY_ANCILLARY_RESULTS("4532"),
  REMAND_IN_CUSTODY_AFTER_BAIL_APPEAL_BY_PROSECUTOR("4534"),
  REMAND_IN_CUSTODY_TO_CUSTOMS_DETENTION("4535"),
  REMAND_IN_CUSTODY_TO_HOSPITAL_MENTAL_HEALTH_ACT("4536"),
  REMAND_IN_LOCAL_AUTHORITY_ACCOMMODATION_BAIL_REFUSED("4537"),
  REMAND_IN_SECURE_LOCAL_AUTHORITY_ACCOMMODATION("4539"),
  REMITTAL_TO_YOUTH_COURT_IN_CUSTODY("4549"),
  CASE_RESCHEDULED_NOT_BAILED("4553"),
  CASE_RESCHEDULED_NOT_BAILED_PERSONAL_SERVICE("4554"),
  COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY("4560"),
  COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY_WITH_DIRECTION_TO_BAIL("4561"),
  COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_SECURE_LOCAL_AUTHORITY_ACCOMMODATION("4563"),
  COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY_TRANSFER_DIRECTION("4564"),
  COMMIT_TO_CROWN_COURT_FOR_TRIAL_SUMMARY_EITHER_WAY_OFFENCES("4565"),
  MENTAL_HEALTH_COMMIT_TO_CROWN_COURT_FOR_RESTRICTION_REMAND_TO_HOSPITAL("4570"),
  MENTAL_HEALTH_COMMIT_TO_CROWN_COURT_FOR_RESTRICTION_REMAND_TO_PRISON("4571"),
  REMITTAL_FOR_TRIAL_IN_CUSTODY("4588"),
  CIVIL_REMAND("5601"),
  ;

  companion object {
    fun getRemandCourtCodes() = entries.map { it.code }
  }
}
