coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  require_head: no
  require_base: no
  require_changes: false
  layout: "reach,diff,files"
  behavior: default
