version: 2.1
orbs:
  hmpps: ministryofjustice/hmpps@11
  codecov: codecov/codecov@3.2.0
parameters:
  releases-slack-channel:
    type: string
    default: the_elephants_devs
  java-version:
    type: string
    default: "21.0"
  localstack-version:
    type: string
    default: "3.0.2"
  postgres-version:
    type: string
    default: "17.5"
jobs:
  validate:
    executor:
      name: hmpps/java
      tag: << pipeline.parameters.java-version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check
      - codecov/upload:
          file: build/reports/jacoco/test/jacocoTestReport.xml
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - store_artifacts:
          path: build/reports/jacoco
  integration-test:
        docker:
          - image: cimg/base:stable
        environment:
          POSTGRES_VERSION: "17.5"
          POSTGRES_DB: "create-and-vary-a-licence-db"
          POSTGRES_USER: "cvl"
          POSTGRES_PASSWORD: "cvl"
          POSTGRES_PORT: "5433"
          LOCALSTACK_VERSION: "3.0.2"
          LOCALSTACK_SERVICES: "sqs,sns"
        steps:
          - checkout
          - run:
              name: Create Docker network
              command: docker network create test-net
          - run:
              name: Start PostgreSQL in memory (tmpfs)
              command: |
                docker run -d \
                  --rm \
                  --name postgres \
                  --network test-net \
                  -e POSTGRES_DB=$POSTGRES_DB \
                  -e POSTGRES_USER=$POSTGRES_USER \
                  -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
                  --tmpfs /var/lib/postgresql/data \
                  -p $POSTGRES_PORT:5432 \
                  postgres:$POSTGRES_VERSION
          - run:
              name: Start LocalStack
              command: |
                docker run -d \
                  --rm \
                  --name localstack \
                  --network test-net \
                  -e SERVICES=$LOCALSTACK_SERVICES \
                  -e DEFAULT_REGION=eu-west-2 \
                  -p 4566:4566 \
                  localstack/localstack:$LOCALSTACK_VERSION
          - run:
              name: Wait for services to be ready
              command: |
                echo "Waiting for PostgreSQL..."
                for i in $(seq 1 30); do
                  nc -z localhost $POSTGRES_PORT && break
                  sleep 1
                done
                echo "PostgreSQL is up!"

                echo "Waiting for LocalStack..."
                for i in $(seq 1 30); do
                  nc -z localhost 4566 && break
                  sleep 1
                done
                echo "LocalStack is up!"

          - run:
              name: Run integration tests
              command: ./gradlew integrationTest
          - save_cache:
              paths:
                - ~/.gradle
              key: gradle-{{ checksum "build.gradle.kts" }}
          - store_test_results:
              path: build/test-results
          - store_artifacts:
              path: build/reports/tests
  integration-test-old:
    executor:
      name: hmpps/java_localstack_postgres_with_db_name
      jdk_tag: << pipeline.parameters.java-version >>
      localstack_tag: << pipeline.parameters.localstack-version >>
      postgres_tag: << pipeline.parameters.postgres-version >>
      postgres_db: create-and-vary-a-licence-db
      postgres_username: cvl
      postgres_password: cvl
      postgres_port: 5433
      java_options: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=1
      services: "sns,sqs"
    steps:
      - run:
          command: |
              while true; do
                sleep 5
                ps auxwwf
                echo "======"
              done
          background: true
      - checkout
      - hmpps/wait_till_ready_postgres:
          port: 5433
      - hmpps/wait_till_ready
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" integrationTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/database_schema_report:
            jdk_tag: << pipeline.parameters.java-version >>
            localstack_tag: << pipeline.parameters.localstack-version >>
            postgres_tag: << pipeline.parameters.postgres-version >>
            database_name: create-and-vary-a-licence-db
            user: cvl
            password: cvl
            port: 5433
            initialise_database: "./gradlew initialiseDatabase"
            filters:
              branches:
                only:
                  - main
      - validate:
          filters:
            tags:
              ignore: /.*/
      - integration-test:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
                - /test.*/
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - integration-test
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - create-and-vary-a-licence-api-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - create-and-vary-a-licence-api-prod
          requires:
            - request-prod-approval
      - hmpps/deploy_env:
          name: deploy_test1
          env: "test1"
          context:
            - hmpps-common-vars
            - create-and-vary-a-licence-test1
          requires:
            - build_docker
          filters:
            branches:
              only:
                - test1
      - hmpps/deploy_env:
          name: deploy_test2
          env: "test2"
          context:
            - hmpps-common-vars
            - create-and-vary-a-licence-test2
          requires:
            - build_docker
          filters:
            branches:
              only:
                - main
