package uk.gov.justice.digital.hmpps.createandvaryalicenceapi.service

import org.springframework.stereotype.Service
import uk.gov.justice.digital.hmpps.createandvaryalicenceapi.service.prison.PrisonApiClient
import uk.gov.justice.digital.hmpps.createandvaryalicenceapi.service.prison.PrisonerSearchPrisoner

@Service
class RemandDeterminationService(
  private val prisonApiClient: PrisonApiClient,
) {

  fun isRemandCase(prisoner: PrisonerSearchPrisoner) = getRemandBookingIds(listOf(prisoner)).isNotEmpty()

  fun getRemandBookingIds(prisoners: List<PrisonerSearchPrisoner>): List<Long> {
    val potentialRemandBookings = prisoners.mapNotNull { it.bookingId?.toLong() }
    val courtEventOutcomes = prisonApiClient.getCourtEventOutcomes(potentialRemandBookings, REMAND_RESULT_CODES)
    return courtEventOutcomes.map { it.bookingId }
  }

  private companion object RemandConstants {
    const val BAIL_APPEAL_WITHDRAWN = "2507"
    const val COMMITED_TO_CROWN_COURT_FOR_SENTENCE = "4001"
    const val SENTENCE_POSTPONED = "4004"
    const val REMITTAL_FOR_SENTENCE_IN_CUSTODY = "4012"
    const val COMMIT_TO_CROWN_COURT_FOR_SENTENCE_IN_CUSTODY = "4016"
    const val WARRANT_FOR_FURTHER_DETENTION = "4505"
    const val ADJOURNMENT = "4506"
    const val REMAND_IN_CUSTODY_BAIL_REFUSED = "4531"
    const val REMAND_IN_CUSTODY_ANCILLARY_RESULTS = "4532"
    const val REMAND_IN_CUSTODY_AFTER_BAIL_APPEAL_BY_PROSECUTOR = "4534"
    const val REMAND_IN_CUSTODY_TO_CUSTOMS_DETENTION = "4535"
    const val REMAND_IN_CUSTODY_TO_HOSPITAL_MENTAL_HEALTH_ACT = "4536"
    const val REMAND_IN_LOCAL_AUTHORITY_ACCOMMODATION_BAIL_REFUSED = "4537"
    const val REMAND_IN_SECURE_LOCAL_AUTHORITY_ACCOMMODATION = "4539"
    const val REMITTAL_TO_YOUTH_COURT_IN_CUSTODY = "4549"
    const val CASE_RESCHEDULED_NOT_BAILED = "4553"
    const val CASE_RESCHEDULED_NOT_BAILED_PERSONAL_SERVICE = "4554"
    const val COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY = "4560"
    const val COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY_WITH_DIRECTION_TO_BAIL = "4561"
    const val COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_SECURE_LOCAL_AUTHORITY_ACCOMMODATION = "4563"
    const val COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY_TRANSFER_DIRECTION = "4564"
    const val COMMIT_TO_CROWN_COURT_FOR_TRIAL_SUMMARY_EITHER_WAY_OFFENCES = "4565"
    const val MENTAL_HEALTH_COMMIT_TO_CROWN_COURT_FOR_RESTRICTION_REMAND_TO_HOSPITAL = "4570"
    const val MENTAL_HEALTH_COMMIT_TO_CROWN_COURT_FOR_RESTRICTION_REMAND_TO_PRISON = "4571"
    const val REMITTAL_FOR_TRIAL_IN_CUSTODY = "4588"
    const val CIVIL_REMAND = "5601"

    val REMAND_RESULT_CODES =
      listOf(BAIL_APPEAL_WITHDRAWN, COMMITED_TO_CROWN_COURT_FOR_SENTENCE, SENTENCE_POSTPONED, REMITTAL_FOR_SENTENCE_IN_CUSTODY, COMMIT_TO_CROWN_COURT_FOR_SENTENCE_IN_CUSTODY, WARRANT_FOR_FURTHER_DETENTION, ADJOURNMENT, REMAND_IN_CUSTODY_BAIL_REFUSED, REMAND_IN_CUSTODY_ANCILLARY_RESULTS, REMAND_IN_CUSTODY_AFTER_BAIL_APPEAL_BY_PROSECUTOR, REMAND_IN_CUSTODY_TO_CUSTOMS_DETENTION, REMAND_IN_CUSTODY_TO_HOSPITAL_MENTAL_HEALTH_ACT, REMAND_IN_LOCAL_AUTHORITY_ACCOMMODATION_BAIL_REFUSED, REMAND_IN_SECURE_LOCAL_AUTHORITY_ACCOMMODATION, REMITTAL_TO_YOUTH_COURT_IN_CUSTODY, CASE_RESCHEDULED_NOT_BAILED, CASE_RESCHEDULED_NOT_BAILED_PERSONAL_SERVICE, COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY, COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY_WITH_DIRECTION_TO_BAIL, COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_SECURE_LOCAL_AUTHORITY_ACCOMMODATION, COMMIT_TRANSFER_SEND_TO_CROWN_COURT_FOR_TRIAL_IN_CUSTODY_TRANSFER_DIRECTION, COMMIT_TO_CROWN_COURT_FOR_TRIAL_SUMMARY_EITHER_WAY_OFFENCES, MENTAL_HEALTH_COMMIT_TO_CROWN_COURT_FOR_RESTRICTION_REMAND_TO_HOSPITAL, MENTAL_HEALTH_COMMIT_TO_CROWN_COURT_FOR_RESTRICTION_REMAND_TO_PRISON, REMITTAL_FOR_TRIAL_IN_CUSTODY, CIVIL_REMAND)
  }
}
