---
# Per environment values which override defaults in create-and-vary-a-licence-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    hosts:
      - create-and-vary-a-licence-api-test2.hmpps.service.justice.gov.uk
    contextColour: green

  serviceAccountName: create-and-vary-a-licence

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_AUTH_TOKEN_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token"
    HMPPS_COMMUNITY_API_URL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
    HMPPS_DOCUMENT_API_URL: "https://document-api-dev.hmpps.service.justice.gov.uk/"
    HMPPS_PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk/api"
    HMPPS_PRISONREGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    HMPPS_PRISONERSEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    HMPPS_PROBATIONSEARCH_API_URL: "https://probation-offender-search-dev.hmpps.service.justice.gov.uk"
    SELF_LINK: "https://create-and-vary-a-licence-test2.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: cvl-alerts-non-prod

dataExtractorEnabled: false
