---
# Per environment values which override defaults in create-and-vary-a-licence-api/values.yaml
generic-service:
  replicaCount: 2

  ingress:
    hosts:
      - create-and-vary-a-licence-api-dev.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_AUTH_TOKEN_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token"
    HMPPS_DELIUS_API_URL: "https://cvl-probation-mock.hmpps.service.justice.gov.uk"
    HMPPS_DOCUMENT_API_URL: "https://document-api-dev.hmpps.service.justice.gov.uk/"
    HMPPS_HDC_API_URL: "https://hdc-api-dev.hmpps.service.justice.gov.uk/"
    HMPPS_MANAGEUSERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk/api"
    HMPPS_PRISONREGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    HMPPS_PRISONERSEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    SELF_LINK: "https://create-and-vary-a-licence-dev.hmpps.service.justice.gov.uk"
    SELF_API_LINK: "https://create-and-vary-a-licence-api-dev.hmpps.service.justice.gov.uk"
    OS_PLACES_API_URL: "https://api.os.uk/search/places/v1"
    HARDSTOP_ENABLED: false
    DOMAIN_EVENT_LISTENER_ENABLED: true
    UPDATE_OFFENDER_DETAILS_HANDLER_ENABLED: false

  namespace_secrets:
    sqs-domain-events-queue-secret:
      HMPPS_SQS_QUEUES_DOMAINEVENTSQUEUE_QUEUE_NAME: "sqs_queue_name"

  scheduledDowntime:
    enabled: true
    businessHoursOnly: true

#CloudPlatform AlertManager receiver to route prometheus alerts to slack
#See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: cvl-alerts-non-prod

jobs:
  - name: prompt-licence-creation-job
    enabled: true
    path: /prompt-licence-creation
    cron: "0 9 * * 1" # 9am UTC, Monday
    allowRetry: false

  - name: deactivate-hdc-licences-job
    enabled: true
    path: /deactivate-hdc-licences
    cron: "30 9 * * 1-5" # 9:30am UTC Monday - Friday
    allowRetry: true

  - name: activate-licences-job
    enabled: true
    path: /activate-licences
    cron: "0 9,12,15,18 * * 1-5"  # 9am, 12pm, 3pm, and 6pm UTC Monday - Friday
    allowRetry: true

  - name: deactivate-licences-past-release-date-job
    enabled: true
    path: /deactivate-licences-past-release-date
    cron: "0 7 * * 1-5" # 7am UTC Monday - Friday
    allowRetry: true

  - name: expire-licences-job
    enabled: true
    path: /expire-licences
    cron: "0 10 * * 1-5" # 10am UTC, Monday - Friday
    allowRetry: true

  - name: warn-hard-stop-review-overdue-job
    enabled: true
    path: /warn-hard-stop-review-overdue
    cron: "0 8 * * 1-5" # 8am UTC Monday - Friday
    allowRetry: false

  - name: time-out-licences-job
    enabled: true
    path: /time-out-licences
    cron: "30 7 * * 1-5" # 7:30am UTC Monday - Friday
    allowRetry: true

  - name: remove-expired-conditions-job
    enabled: true
    path: /remove-expired-conditions
    cron: "0 7 * * 1-5" # 7am UTC, Monday - Friday
    allowRetry: true

  - name: notify-probation-of-unapproved-licences-job
    enabled: true
    path: /notify-probation-of-unapproved-licences
    cron: "0 11 * * 1-5" # 11am UTC, Monday - Friday
    allowRetry: false
