UPDATE licence_event
SET event_type = CASE
                     WHEN event_type = 'HARD_STOP_REVIEWED_WITHOUT_VARIATION' THEN 'REVIEWED_WITHOUT_VARIATION'
                     WHEN event_type = 'HARD_STOP_REVIEWED_WITH_VARIATION' THEN 'REVIEWED_WITH_VARIATION'
    END
WHERE event_type IN ('HARD_STOP_REVIEWED_WITHOUT_VARIATION', 'HARD_STOP_REVIEWED_WITH_VARIATION');
